language: php
php:
  - '5.6'
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

install: composer require

script:
 - php sample/avifdump.php -f avif-samples/bbb_4k.avif
 - php sample/aviftree.php -f avif-samples/bbb_4k.avif
